# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='books',
            new_name='articles',
        ),
    ]
