# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-07 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160905_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
